CREATE DATABASE Gym
USE Gym

-- 1.
CREATE TABLE CLIENTE (
ClienteID INT PRIMARY KEY IDENTITY(1,1),
Nombre NVARCHAR(50) NOT NULL,
Apellido NVARCHAR(50) NOT NULL,
Telefono INT,
ModifiedDate DATETIME DEFAULT GETDATE(),
UNIQUE(Telefono)
)

-- 2.
CREATE TABLE SERVICIO (
ServicioID INT PRIMARY KEY IDENTITY(1,1),
Nombre NVARCHAR(50) NOT NULL,
HoraInicio TIME NOT NULL,
HoraFin TIME NOT NULL,
ModifiedDate DATETIME DEFAULT GETDATE()
)

-- 3.
CREATE TABLE INSCRIPCION (
InscripcionID INT PRIMARY KEY IDENTITY(1,1),
ClienteID INT NOT NULL,
FOREIGN KEY (ClienteID) REFERENCES CLIENTE(ClienteID),
CantidadMeses INT NOT NULL,
FechaInicio DATE NOT NULL,
FechaFin AS (DATEADD(MONTH, CantidadMeses, FechaInicio)) PERSISTED,
Mensualidad INT NOT NULL DEFAULT 250,
PrecioTotal AS (Mensualidad * CantidadMeses) PERSISTED,
ModifiedDate DATETIME DEFAULT GETDATE()
)

-- 4.
CREATE TABLE PAGOS (
PagoID INT PRIMARY KEY IDENTITY(1,1),
InscripcionID INT NOT NULL,
FOREIGN KEY (InscripcionID) REFERENCES INSCRIPCION(InscripcionID),
Fecha DATE NOT NULL,
Total DECIMAL(10,2) NOT NULL,
DescuentoID INT,
TotalFinal DECIMAL(10,2),
ModifiedDate DATETIME DEFAULT GETDATE()
)

-- 5.
CREATE TABLE ASISTENCIA (
AsistenciaID INT PRIMARY KEY IDENTITY(1,1),
InscripcionID INT NOT NULL,
ServicioID INT,
FOREIGN KEY (InscripcionID) REFERENCES INSCRIPCION(InscripcionID),
FOREIGN KEY (ServicioID) REFERENCES SERVICIO(ServicioID),
Fecha DATE NOT NULL,
HoraIngreso TIME,
UNIQUE(InscripcionID, Fecha),
ModifiedDate DATETIME DEFAULT GETDATE()
)

-- 6.
CREATE TABLE ENTRENADORES (
EntrenadorID INT PRIMARY KEY IDENTITY(1,1),
ServicioID INT NOT NULL, FOREIGN KEY (ServicioID) REFERENCES SERVICIO(ServicioID),
Nombre NVARCHAR(50) NOT NULL,
Apellido NVARCHAR(50) NOT NULL,
Telefono INT,
Correo NVARCHAR(50),
FechaInicio DATE NOT NULL,
FechaFin DATE,
Sueldo INT NOT NULL,
Turno NVARCHAR(50),
Estado AS (
	CASE WHEN FechaFin IS NULL THEN 'Activo'
	ELSE 'Despedido'
	END
	) PERSISTED,
ModifiedDate DATETIME DEFAULT GETDATE()
)

-- 7.
CREATE TABLE INVENTARIO (
    EquipoID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(255) NOT NULL,
    Cantidad INT DEFAULT 1,
    Estado NVARCHAR(50) CHECK (Estado IN ('Nuevo', 'En Uso', 'Mantenimiento', 'Mal Estado', 'Descontinuado')),
    FechaAdquisicion DATE NOT NULL,
    ServicioID INT NOT NULL,
    ModifiedDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ServicioID) REFERENCES SERVICIO(ServicioID) 
);

-- 8.
CREATE TABLE DESCUENTOS (
    DescuentoID INT PRIMARY KEY IDENTITY(1,1),
    Nombre NVARCHAR(50) NOT NULL,
    Porcentaje DECIMAL(5,2) CHECK (Porcentaje BETWEEN 0 AND 100),
    FechaInicio DATE NOT NULL,
    FechaFin DATE NOT NULL,
    Estado NVARCHAR(20) DEFAULT 'Activo',
	ModifiedDate DATETIME DEFAULT GETDATE()
);